/*GENERATED BY OBNC 0.9.1*/

#include <obnc/OBNC.h>
#include "In.h"

int In_Done_;

void In_Open_(void)
{
}


void In_Char_(char *ch_)
{
}


void In_Int_(int *i_)
{
}


void In_Real_(double *x_)
{
}


void In_String_(char str_[], int str_len)
{
}


void In_Name_(char name_[], int name_len)
{
}


void In_Init(void)
{
}
