/*GENERATED BY OBNC 0.9.1*/

#ifndef In_h
#define In_h

#include <obnc/OBNC.h>

#define In_Done_ obnc_In_Done_
extern int In_Done_;

#define In_Open_ obnc_In_Open_
void In_Open_(void);

#define In_Char_ obnc_In_Char_
void In_Char_(char *ch_);

#define In_Int_ obnc_In_Int_
void In_Int_(int *i_);

#define In_Real_ obnc_In_Real_
void In_Real_(double *x_);

#define In_String_ obnc_In_String_
void In_String_(char str_[], int str_len);

#define In_Name_ obnc_In_Name_
void In_Name_(char name_[], int name_len);

#define In_Init obnc_In_Init
void In_Init(void);

#endif
