/*GENERATED BY OBNC 0.9.1*/

#ifndef Input_h
#define Input_h

#include <obnc/OBNC.h>

#define Input_TimeUnit_ obnc_Input_TimeUnit_
extern int Input_TimeUnit_;

#define Input_Available_ obnc_Input_Available_
int Input_Available_(void);

#define Input_Read_ obnc_Input_Read_
void Input_Read_(char *ch_);

#define Input_Mouse_ obnc_Input_Mouse_
void Input_Mouse_(unsigned int *keys_, int *x_, int *y_);

#define Input_SetMouseLimits_ obnc_Input_SetMouseLimits_
void Input_SetMouseLimits_(int w_, int h_);

#define Input_Time_ obnc_Input_Time_
int Input_Time_(void);

#define Input_Init obnc_Input_Init
void Input_Init(void);

#endif
