/*GENERATED BY OBNC 0.9.1*/

#include <obnc/OBNC.h>
#include "Strings.h"

int Strings_Length_(const char s_[], int s_len)
{
	int i_;

	i_ = 0;
	while (s_[OBNC_IT(i_, s_len)] != '\x0') {
		OBNC_INC(i_);
	}
	return i_;
}


static int Min2_(int a_, int b_)
{
	int result_;

	if (a_ < b_) {
		result_ = a_;
	}
	else {
		result_ = b_;
	}
	return result_;
}


static int Min3_(int a_, int b_, int c_)
{
	int result_;

	result_ = a_;
	if (b_ < result_) {
		result_ = b_;
	}
	if (c_ < result_) {
		result_ = c_;
	}
	return result_;
}


void Strings_Insert_(const char source_[], int source_len, int pos_, char dest_[], int dest_len)
{
	int sourceLength_, destLength_, newLength_;
	int i_, lim_;

	destLength_ = Strings_Length_(dest_, dest_len);
	OBNC_ASSERT(pos_ >= 0, "Strings.obn", 67);
	OBNC_ASSERT(pos_ <= destLength_, "Strings.obn", 68);
	sourceLength_ = Strings_Length_(source_, source_len);
	newLength_ = Min2_((destLength_ + sourceLength_), (dest_len - 1));
	dest_[OBNC_IT(newLength_, dest_len)] = '\x0';
	for (i_ = newLength_ - 1; i_ >= pos_ + sourceLength_; i_ += -1) {
		dest_[OBNC_IT(i_, dest_len)] = dest_[OBNC_IT(i_ - sourceLength_, dest_len)];
	}
	lim_ = Min2_(((pos_ + sourceLength_) - 1), (newLength_ - 1));
	for (i_ = pos_; i_ <= lim_; i_ += 1) {
		dest_[OBNC_IT(i_, dest_len)] = source_[OBNC_IT(i_ - pos_, source_len)];
	}
}


void Strings_Append_(const char extra_[], int extra_len, char dest_[], int dest_len)
{
	int destLength_, newLength_;
	int i_;

	destLength_ = Strings_Length_(dest_, dest_len);
	newLength_ = Min2_((destLength_ + Strings_Length_(extra_, extra_len)), (dest_len - 1));
	for (i_ = destLength_; i_ <= newLength_ - 1; i_ += 1) {
		dest_[OBNC_IT(i_, dest_len)] = extra_[OBNC_IT(i_ - destLength_, extra_len)];
	}
	dest_[OBNC_IT(newLength_, dest_len)] = '\x0';
}


void Strings_Delete_(char s_[], int s_len, int pos_, int n_)
{
	int length_, n1_, i_;

	length_ = Strings_Length_(s_, s_len);
	OBNC_ASSERT(pos_ >= 0, "Strings.obn", 107);
	OBNC_ASSERT(pos_ <= length_, "Strings.obn", 108);
	OBNC_ASSERT(n_ >= 0, "Strings.obn", 109);
	n1_ = Min2_(n_, (length_ - pos_));
	for (i_ = pos_; i_ <= length_ - n1_; i_ += 1) {
		s_[OBNC_IT(i_, s_len)] = s_[OBNC_IT(i_ + n1_, s_len)];
	}
}


void Strings_Replace_(const char source_[], int source_len, int pos_, char dest_[], int dest_len)
{
	int destLength_, n_, i_;

	destLength_ = Strings_Length_(dest_, dest_len);
	OBNC_ASSERT(pos_ >= 0, "Strings.obn", 123);
	OBNC_ASSERT(pos_ <= destLength_, "Strings.obn", 124);
	n_ = Min2_(Strings_Length_(source_, source_len), ((dest_len - 1) - pos_));
	for (i_ = 0; i_ <= n_ - 1; i_ += 1) {
		dest_[OBNC_IT(pos_ + i_, dest_len)] = source_[OBNC_IT(i_, source_len)];
	}
	if ((pos_ + n_) > destLength_) {
		dest_[OBNC_IT(pos_ + n_, dest_len)] = '\x0';
	}
}


void Strings_Extract_(const char source_[], int source_len, int pos_, int n_, char dest_[], int dest_len)
{
	int sourceLength_, n1_, i_;

	sourceLength_ = Strings_Length_(source_, source_len);
	OBNC_ASSERT(pos_ >= 0, "Strings.obn", 144);
	OBNC_ASSERT(pos_ <= sourceLength_, "Strings.obn", 145);
	n1_ = Min3_(n_, (sourceLength_ - pos_), (dest_len - 1));
	for (i_ = 0; i_ <= n1_ - 1; i_ += 1) {
		dest_[OBNC_IT(i_, dest_len)] = source_[OBNC_IT(pos_ + i_, source_len)];
	}
	dest_[OBNC_IT(n1_, dest_len)] = '\x0';
}


int Strings_Pos_(const char pattern_[], int pattern_len, const char s_[], int s_len, int pos_);

static int Pos_StartsWith_Local(const char pattern_[], int pattern_len, int patLength_, const char s_[], int s_len, int pos_)
{
	int i_;

	i_ = 0;
	while ((i_ < patLength_) && (pattern_[OBNC_IT(i_, pattern_len)] == s_[OBNC_IT(pos_ + i_, s_len)])) {
		OBNC_INC(i_);
	}
	return i_ == patLength_;
}


int Strings_Pos_(const char pattern_[], int pattern_len, const char s_[], int s_len, int pos_)
{
	int result_, patLength_, sLength_;

	sLength_ = Strings_Length_(s_, s_len);
	OBNC_ASSERT(pos_ >= 0, "Strings.obn", 171);
	OBNC_ASSERT(pos_ <= sLength_, "Strings.obn", 172);
	result_ = -1;
	if (OBNC_CMP(pattern_, pattern_len, "", 1) != 0) {
		patLength_ = Strings_Length_(pattern_, pattern_len);
		OBNC_DEC(pos_);
		do {
			OBNC_INC(pos_);
			while (((pos_ + patLength_) <= sLength_) && (s_[OBNC_IT(pos_, s_len)] != pattern_[0])) {
				OBNC_INC(pos_);
			}
		} while (! (((pos_ + patLength_) > sLength_) || Pos_StartsWith_Local(pattern_, pattern_len, patLength_, s_, s_len, pos_)));
		if ((pos_ + patLength_) <= sLength_) {
			result_ = pos_;
		}
	}
	OBNC_ASSERT(result_ >= -1, "Strings.obn", 187);
	OBNC_ASSERT(result_ < sLength_, "Strings.obn", 189);
	return result_;
}


void Strings_Cap_(char s_[], int s_len)
{
	int i_;

	i_ = 0;
	while (s_[OBNC_IT(i_, s_len)] != '\x0') {
		if (((unsigned char) s_[OBNC_IT(i_, s_len)] >= (unsigned char) 'a') && ((unsigned char) s_[OBNC_IT(i_, s_len)] <= (unsigned char) 'z')) {
			s_[OBNC_IT(i_, s_len)] = OBNC_CHR((65 + OBNC_ORD((unsigned char) s_[OBNC_IT(i_, s_len)])) - 97);
		}
		OBNC_INC(i_);
	}
}


void Strings_Init(void)
{
}
