#!/bin/sh

# Copyright 2017 Karl Landstrom <karl@miasap.se>
#
# This file is part of obnc-libstd.
#
# obnc-libstd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# obnc-libstd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with obnc-libstd.  If not, see <http://www.gnu.org/licenses/>.

set -o errexit

readonly selfDirPath="$(cd "$(dirname "$0")"; pwd -P)"
readonly packageName="$(basename "$selfDirPath")"
readonly packageNameSansVersion="${packageName%-[0-9]*}"
readonly libName="${packageNameSansVersion#obnc-lib}"

if [ "$#" -eq 0 ]; then
	cd "$selfDirPath/$libName"
	for file in *Test.obn; do
		obnc "$file" > /dev/null
		module="${file%.obn}"
		if [ -e "$module.sh" ]; then
			"./$module.sh"
		else
			"./$module"
		fi
	done
else
	echo "usage: $(basename "$0")" >&2
	exit 1
fi
