/*GENERATED BY OBNC 0.8.4*/

#include "Files.h"

const int Files_Handle_id;
const int *const Files_Handle_ids[1] = {&Files_Handle_id};
const OBNC_Td Files_Handle_td = {Files_Handle_ids, 1};

const int Files_Rider_id;
const int *const Files_Rider_ids[1] = {&Files_Rider_id};
const OBNC_Td Files_Rider_td = {Files_Rider_ids, 1};

Files_File_ Files_Old_(const char name_[], int name_len)
{
	return 0;
}


Files_File_ Files_New_(const char name_[], int name_len)
{
	return 0;
}


void Files_Register_(Files_File_ f_)
{
}


void Files_Close_(Files_File_ f_)
{
}


void Files_Purge_(Files_File_ f_)
{
}


void Files_Delete_(const char name_[], int name_len, int *res_)
{
}


void Files_Rename_(const char old_[], int old_len, const char new_[], int new_len, int *res_)
{
}


int Files_Length_(Files_File_ f_)
{
	return 0;
}


void Files_GetDate_(Files_File_ f_, int *t_, int *d_)
{
}


void Files_Set_(Files_Rider_ *r_, const OBNC_Td *r_td, Files_File_ f_, int pos_)
{
}


int Files_Pos_(Files_Rider_ *r_, const OBNC_Td *r_td)
{
	return 0;
}


Files_File_ Files_Base_(Files_Rider_ *r_, const OBNC_Td *r_td)
{
	return 0;
}


void Files_Read_(Files_Rider_ *r_, const OBNC_Td *r_td, unsigned char *x_)
{
}


void Files_ReadInt_(Files_Rider_ *r_, const OBNC_Td *r_td, int *i_)
{
}


void Files_ReadReal_(Files_Rider_ *r_, const OBNC_Td *r_td, double *x_)
{
}


void Files_ReadNum_(Files_Rider_ *r_, const OBNC_Td *r_td, int *i_)
{
}


void Files_ReadString_(Files_Rider_ *r_, const OBNC_Td *r_td, char s_[], int s_len)
{
}


void Files_ReadSet_(Files_Rider_ *r_, const OBNC_Td *r_td, unsigned int *s_)
{
}


void Files_ReadBool_(Files_Rider_ *r_, const OBNC_Td *r_td, int *b_)
{
}


void Files_ReadBytes_(Files_Rider_ *r_, const OBNC_Td *r_td, unsigned char buf_[], int buf_len, int n_)
{
}


void Files_Write_(Files_Rider_ *r_, const OBNC_Td *r_td, unsigned char x_)
{
}


void Files_WriteInt_(Files_Rider_ *r_, const OBNC_Td *r_td, int i_)
{
}


void Files_WriteReal_(Files_Rider_ *r_, const OBNC_Td *r_td, double x_)
{
}


void Files_WriteNum_(Files_Rider_ *r_, const OBNC_Td *r_td, int i_)
{
}


void Files_WriteString_(Files_Rider_ *r_, const OBNC_Td *r_td, const char s_[], int s_len)
{
}


void Files_WriteSet_(Files_Rider_ *r_, const OBNC_Td *r_td, unsigned int s_)
{
}


void Files_WriteBool_(Files_Rider_ *r_, const OBNC_Td *r_td, int b_)
{
}


void Files_WriteBytes_(Files_Rider_ *r_, const OBNC_Td *r_td, unsigned char buf_[], int buf_len, int n_)
{
}


void Files_Init(void)
{
}
