/*GENERATED BY OBNC 0.8.4*/

#include "/home/gunter/GM_LANGUAGES/OBERON/V_07/OBNC/obnc-0.8.4/lib/obnc/OBNC_.h"
#include "Input.h"
#include "Out.h"
#include "XYplane.h"

int main(int argc, char *argv[])
{
	OBNC_Initialize(argc, argv);
	Input_Init();
	Out_Init();
	XYplane_Init();
	return 0;
}
