/*GENERATED BY OBNC 0.8.4*/

#include "Input.h"

int Input_TimeUnit_;

int Input_Available_(void)
{
	return 0;
}


void Input_Read_(char *ch_)
{
}


void Input_Mouse_(unsigned int *keys_, int *x_, int *y_)
{
}


void Input_SetMouseLimits_(int w_, int h_)
{
}


int Input_Time_(void)
{
	return 0;
}


void Input_Init(void)
{
}
