/*GENERATED BY OBNC 0.8.4*/

#include "Math.h"

double Math_sqrt_(double x_)
{
	return 0.0;
}


double Math_power_(double base_, double exp_)
{
	return 0.0;
}


double Math_exp_(double x_)
{
	return 0.0;
}


double Math_ln_(double x_)
{
	return 0.0;
}


double Math_log_(double x_, double base_)
{
	return 0.0;
}


double Math_round_(double x_)
{
	return 0.0;
}


double Math_sin_(double x_)
{
	return 0.0;
}


double Math_cos_(double x_)
{
	return 0.0;
}


double Math_tan_(double x_)
{
	return 0.0;
}


double Math_arcsin_(double x_)
{
	return 0.0;
}


double Math_arccos_(double x_)
{
	return 0.0;
}


double Math_arctan_(double x_)
{
	return 0.0;
}


double Math_arctan2_(double y_, double x_)
{
	return 0.0;
}


double Math_sinh_(double x_)
{
	return 0.0;
}


double Math_cosh_(double x_)
{
	return 0.0;
}


double Math_tanh_(double x_)
{
	return 0.0;
}


double Math_arcsinh_(double x_)
{
	return 0.0;
}


double Math_arccosh_(double x_)
{
	return 0.0;
}


double Math_arctanh_(double x_)
{
	return 0.0;
}


void Math_Init(void)
{
}
