/*GENERATED BY OBNC 0.8.4*/

#ifndef Math_h
#define Math_h

#include "/home/gunter/GM_LANGUAGES/OBERON/V_07/OBNC/obnc-0.8.4/lib/obnc/OBNC_.h"

#define Math_pi_ 3.14159265358979

#define Math_e_ 2.71828182845905

#define Math_sqrt_ obnc_Math_sqrt_
double Math_sqrt_(double x_);

#define Math_power_ obnc_Math_power_
double Math_power_(double base_, double exp_);

#define Math_exp_ obnc_Math_exp_
double Math_exp_(double x_);

#define Math_ln_ obnc_Math_ln_
double Math_ln_(double x_);

#define Math_log_ obnc_Math_log_
double Math_log_(double x_, double base_);

#define Math_round_ obnc_Math_round_
double Math_round_(double x_);

#define Math_sin_ obnc_Math_sin_
double Math_sin_(double x_);

#define Math_cos_ obnc_Math_cos_
double Math_cos_(double x_);

#define Math_tan_ obnc_Math_tan_
double Math_tan_(double x_);

#define Math_arcsin_ obnc_Math_arcsin_
double Math_arcsin_(double x_);

#define Math_arccos_ obnc_Math_arccos_
double Math_arccos_(double x_);

#define Math_arctan_ obnc_Math_arctan_
double Math_arctan_(double x_);

#define Math_arctan2_ obnc_Math_arctan2_
double Math_arctan2_(double y_, double x_);

#define Math_sinh_ obnc_Math_sinh_
double Math_sinh_(double x_);

#define Math_cosh_ obnc_Math_cosh_
double Math_cosh_(double x_);

#define Math_tanh_ obnc_Math_tanh_
double Math_tanh_(double x_);

#define Math_arcsinh_ obnc_Math_arcsinh_
double Math_arcsinh_(double x_);

#define Math_arccosh_ obnc_Math_arccosh_
double Math_arccosh_(double x_);

#define Math_arctanh_ obnc_Math_arctanh_
double Math_arctanh_(double x_);

#define Math_Init obnc_Math_Init
void Math_Init(void);

#endif
