/*GENERATED BY OBNC 0.8.4*/

#include "Out.h"

void Out_Open_(void)
{
}


void Out_Char_(char ch_)
{
}


void Out_String_(const char s_[], int s_len)
{
}


void Out_Int_(int i_, int n_)
{
}


void Out_Real_(double x_, int n_)
{
}


void Out_Ln_(void)
{
}


void Out_Init(void)
{
}
