/*GENERATED BY OBNC 0.8.4*/

#include "/home/gunter/GM_LANGUAGES/OBERON/V_07/OBNC/obnc-0.8.4/lib/obnc/OBNC_.h"
#include "Out.h"

int main(int argc, char *argv[])
{
	OBNC_Initialize(argc, argv);
	Out_Init();
	Out_Char_('a');
	Out_Ln_();
	Out_String_("abc", 4);
	Out_Ln_();
	Out_Int_(-1, 0);
	Out_Ln_();
	Out_Int_(-1, 3);
	Out_Ln_();
	Out_Int_(0, 0);
	Out_Ln_();
	Out_Int_(1, 0);
	Out_Ln_();
	Out_Int_(37, 0);
	Out_Ln_();
	Out_Real_(-1.0, 0);
	Out_Ln_();
	Out_Real_(0.0, 0);
	Out_Ln_();
	Out_Real_(0.0, 14);
	Out_Ln_();
	Out_Real_(1.0, 0);
	Out_Ln_();
	Out_Real_(37.0, 0);
	Out_Ln_();
	Out_Real_(0.37, 0);
	Out_Ln_();
	return 0;
}
