/*GENERATED BY OBNC 0.8.4*/

#include "/home/gunter/GM_LANGUAGES/OBERON/V_07/OBNC/obnc-0.8.4/lib/obnc/OBNC_.h"
#include "Strings.h"

static char shortStr_[4];

static char s_[14];

int main(int argc, char *argv[])
{
	OBNC_Initialize(argc, argv);
	Strings_Init();
	OBNC_ASSERT(Strings_Length_("", 1) == 0, "StringsTest.obn", 28);
	OBNC_COPY_ARRAY("", shortStr_, 1);
	OBNC_ASSERT(Strings_Length_(shortStr_, 4) == 0, "StringsTest.obn", 30);
	OBNC_COPY_ARRAY("\"", shortStr_, 2);
	OBNC_ASSERT(Strings_Length_(shortStr_, 4) == 1, "StringsTest.obn", 32);
	OBNC_COPY_ARRAY("123", shortStr_, 4);
	OBNC_ASSERT(Strings_Length_(shortStr_, 4) == 3, "StringsTest.obn", 34);
	OBNC_COPY_ARRAY("foo baz", s_, 8);
	Strings_Insert_("bar ", 5, 4, s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo bar baz", 12) == 0, "StringsTest.obn", 39);
	OBNC_COPY_ARRAY("foo bar", s_, 8);
	Strings_Insert_(" baz", 5, Strings_Length_(s_, 14), s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo bar baz", 12) == 0, "StringsTest.obn", 42);
	Strings_Insert_(" qux qux qux qux qux", 21, Strings_Length_(s_, 14), s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo bar baz q", 14) == 0, "StringsTest.obn", 44);
	OBNC_COPY_ARRAY("", s_, 1);
	Strings_Append_("foo", 4, s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo", 4) == 0, "StringsTest.obn", 49);
	Strings_Append_(" bar", 5, s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo bar", 8) == 0, "StringsTest.obn", 51);
	Strings_Append_(" baz qux", 9, s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo bar baz q", 14) == 0, "StringsTest.obn", 53);
	OBNC_COPY_ARRAY("foo bar baz", s_, 12);
	Strings_Delete_(s_, 14, 7, 4);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo bar", 8) == 0, "StringsTest.obn", 58);
	Strings_Delete_(s_, 14, 0, 4);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "bar", 4) == 0, "StringsTest.obn", 60);
	Strings_Delete_(s_, 14, 1, 10);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "b", 2) == 0, "StringsTest.obn", 62);
	Strings_Delete_(s_, 14, 0, 0);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "b", 2) == 0, "StringsTest.obn", 64);
	Strings_Delete_(s_, 14, 0, 1);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "", 1) == 0, "StringsTest.obn", 66);
	OBNC_COPY_ARRAY("foo bar baz", s_, 12);
	Strings_Replace_("qux", 4, 4, s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo qux baz", 12) == 0, "StringsTest.obn", 71);
	OBNC_COPY_ARRAY("foo bar", s_, 8);
	Strings_Replace_("qux qux qux", 12, 5, s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "foo bqux qux ", 14) == 0, "StringsTest.obn", 74);
	Strings_Extract_("foo bar", 8, 4, 3, shortStr_, 4);
	OBNC_ASSERT(OBNC_CMP(shortStr_, 4, "bar", 4) == 0, "StringsTest.obn", 78);
	Strings_Extract_("foo bar", 8, 4, 10, shortStr_, 4);
	OBNC_ASSERT(OBNC_CMP(shortStr_, 4, "bar", 4) == 0, "StringsTest.obn", 80);
	Strings_Extract_("foo bar", 8, 0, 6, shortStr_, 4);
	OBNC_ASSERT(OBNC_CMP(shortStr_, 4, "foo", 4) == 0, "StringsTest.obn", 82);
	OBNC_ASSERT(Strings_Pos_("", 1, "", 1, 0) == -1, "StringsTest.obn", 85);
	OBNC_ASSERT(Strings_Pos_("", 1, "foo", 4, 0) == -1, "StringsTest.obn", 86);
	OBNC_ASSERT(Strings_Pos_("foo", 4, "foo", 4, 0) == 0, "StringsTest.obn", 87);
	OBNC_ASSERT(Strings_Pos_("foo", 4, "fool", 5, 0) == 0, "StringsTest.obn", 88);
	OBNC_ASSERT(Strings_Pos_("ool", 4, "fool", 5, 0) == 1, "StringsTest.obn", 89);
	OBNC_ASSERT(Strings_Pos_("oo", 3, "fool", 5, 0) == 1, "StringsTest.obn", 90);
	OBNC_ASSERT(Strings_Pos_("fools", 6, "fool", 5, 0) == -1, "StringsTest.obn", 91);
	OBNC_ASSERT(Strings_Pos_("ol", 3, "fool", 5, 1) == 2, "StringsTest.obn", 92);
	OBNC_ASSERT(Strings_Pos_("fo", 3, "foo", 4, -1) == -1, "StringsTest.obn", 93);
	OBNC_ASSERT(Strings_Pos_("fo", 3, "foo", 4, 4) == -1, "StringsTest.obn", 94);
	OBNC_COPY_ARRAY("foo Bar BAZ", s_, 12);
	Strings_Cap_(s_, 14);
	OBNC_ASSERT(OBNC_CMP(s_, 14, "FOO BAR BAZ", 12) == 0, "StringsTest.obn", 100);
	return 0;
}
