/*GENERATED BY OBNC 0.8.4*/

#ifndef Strings_h
#define Strings_h

#include "/home/gunter/GM_LANGUAGES/OBERON/V_07/OBNC/obnc-0.8.4/lib/obnc/OBNC_.h"

#define Strings_Length_ obnc_Strings_Length_
int Strings_Length_(const char s_[], int s_len);

#define Strings_Insert_ obnc_Strings_Insert_
void Strings_Insert_(const char source_[], int source_len, int pos_, char dest_[], int dest_len);

#define Strings_Append_ obnc_Strings_Append_
void Strings_Append_(const char extra_[], int extra_len, char dest_[], int dest_len);

#define Strings_Delete_ obnc_Strings_Delete_
void Strings_Delete_(char s_[], int s_len, int pos_, int n_);

#define Strings_Replace_ obnc_Strings_Replace_
void Strings_Replace_(const char source_[], int source_len, int pos_, char dest_[], int dest_len);

#define Strings_Extract_ obnc_Strings_Extract_
void Strings_Extract_(const char source_[], int source_len, int pos_, int n_, char dest_[], int dest_len);

#define Strings_Pos_ obnc_Strings_Pos_
int Strings_Pos_(const char pattern_[], int pattern_len, const char s_[], int s_len, int pos_);

#define Strings_Cap_ obnc_Strings_Cap_
void Strings_Cap_(char s_[], int s_len);

#define Strings_Init obnc_Strings_Init
void Strings_Init(void);

#endif
