/*GENERATED BY OBNC 0.8.4*/

#ifndef XYplane_h
#define XYplane_h

#include "/home/gunter/GM_LANGUAGES/OBERON/V_07/OBNC/obnc-0.8.4/lib/obnc/OBNC_.h"
#include "Input.h"

#define XYplane_draw_ 1

#define XYplane_erase_ 0

#define XYplane_X_ obnc_XYplane_X_
#define XYplane_Y_ obnc_XYplane_Y_
extern int XYplane_X_, XYplane_Y_;

#define XYplane_W_ obnc_XYplane_W_
#define XYplane_H_ obnc_XYplane_H_
extern int XYplane_W_, XYplane_H_;

#define XYplane_Open_ obnc_XYplane_Open_
void XYplane_Open_(void);

#define XYplane_Clear_ obnc_XYplane_Clear_
void XYplane_Clear_(void);

#define XYplane_Dot_ obnc_XYplane_Dot_
void XYplane_Dot_(int x_, int y_, int mode_);

#define XYplane_IsDot_ obnc_XYplane_IsDot_
int XYplane_IsDot_(int x_, int y_);

#define XYplane_Key_ obnc_XYplane_Key_
char XYplane_Key_(void);

#define XYplane_Init obnc_XYplane_Init
void XYplane_Init(void);

#endif
